# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

gibbsC <- function(a, b, n, N = 1000L) {
    .Call('_StatComp21090_gibbsC', PACKAGE = 'StatComp21090', a, b, n, N)
}

